/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsheoRouteImport } from './routes/asheo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InProdRouteImport } from './routes/in-prod'
import { Route as OffClockRouteImport } from './routes/off-clock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsheoRoute = AsheoRouteImport.update({
  id: '/asheo',
  path: '/asheo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InProdRoute = InProdRouteImport.update({
  id: '/in-prod',
  path: '/in-prod',
  getParentRoute: () => rootRouteImport,
} as any)
const OffClockRoute = OffClockRouteImport.update({
  id: '/off-clock',
  path: '/off-clock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asheo': typeof AsheoRoute
  '/contact': typeof ContactRoute
  '/in-prod': typeof InProdRoute
  '/off-clock': typeof OffClockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asheo': typeof AsheoRoute
  '/contact': typeof ContactRoute
  '/in-prod': typeof InProdRoute
  '/off-clock': typeof OffClockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asheo': typeof AsheoRoute
  '/contact': typeof ContactRoute
  '/in-prod': typeof InProdRoute
  '/off-clock': typeof OffClockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asheo' | '/contact' | '/in-prod' | '/off-clock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asheo' | '/contact' | '/in-prod' | '/off-clock'
  id: '__root__' | '/' | '/asheo' | '/contact' | '/in-prod' | '/off-clock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsheoRoute: typeof AsheoRoute
  ContactRoute: typeof ContactRoute
  InProdRoute: typeof InProdRoute
  OffClockRoute: typeof OffClockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asheo': {
      id: '/asheo'
      path: '/asheo'
      fullPath: '/asheo'
      preLoaderRoute: typeof AsheoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-prod': {
      id: '/in-prod'
      path: '/in-prod'
      fullPath: '/in-prod'
      preLoaderRoute: typeof InProdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-clock': {
      id: '/off-clock'
      path: '/off-clock'
      fullPath: '/off-clock'
      preLoaderRoute: typeof OffClockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsheoRoute: AsheoRoute,
  ContactRoute: ContactRoute,
  InProdRoute: InProdRoute,
  OffClockRoute: OffClockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
